### PR TITLE
add patchfoo

### PR DESCRIPTION
**Pull request by hackergrrl**

### CODE REVIEW

**Comment by dominictarr** [comment]
thanks! I didn't bother testing this because it would be obviously near zero.
thanks for making this a PR, other people only said "please add X" so I appreciate you took the extra effort ;)

**Comment by hackergrrl** [comment]
you're welcome! I added it because I wanted to have some representation showing "oh hey it IS possible to make responsive low-mem web apps!"

**Comment by dominictarr** [comment]
@noffle it's been a while since I used patchfoo... but it's not "responsive" is it, isn't it just pure html?

**Comment by hackergrrl** [comment]
pure html, aye. it's definitely a "web app" though!

**Comment by hackergrrl** [comment]
TIL: according to [wikipedia](https://en.wikipedia.org/wiki/Responsive_web_design) "responsive" is about working well on devices with different screen sizes. a lot of this stuff seems unrelated to anything you'd need JS for. so maybe patchfoo *is* responsive, since it has the `<meta content="width=device-width,initial-scale=1">` bit to make it play nice on different screen sizes?

**Comment by dominictarr** [comment]
oh, true... pure html is fairly easy to be responsive. I word I was thinking was _dynamic_, you need js for that.

**Pull request merged**
