### PR TITLE
Change the list to a table

### PR DESCRIPTION
**Pull request by ianchanning**
Used an extended markdown table with a right-aligned column for the MB. Makes it easier to scan the sizes

### CODE REVIEW

**Comment by kinow** [comment]
I think it's a good idea. I think it won't allow readers to sort them though? I'm pasting in a local file to use some quick shell and sort locally to review the numbers...

**Comment by ianchanning** [comment]
No - no sorting, I can sort it by default with max MB (worst offenders) at the top

**Comment by ianchanning** [comment]
My latest commit has them sorted now

**Comment by dominictarr** [comment]
thanks!

**Pull request merged**
